spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/springboot
        username: root
        password: root
        # 使用c3p0数据源
        type: com.mchange.v2.c3p0.ComboPooledDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
