server:
  port: 9102
  
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-client-rsa
  datasource:
    url: jdbc:mysql://172.17.86.20:3306/producter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #url: jdbc:mysql://172.17.86.10:3306/producter?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: '{cipher}AQBjH78uMQa5mUssAlaxenaEilawgr8EVarowUPWVYL8YszcswJZ8azOZSAZ/ig+ZDRpaJB+wVj78kaIN2fBMe1679z1IUG1elAuxoX3Ew9ojiS1NiSFFL+Az//1HgaPNh73awE8H2Ou/vMhf97cNUVqRzHIJKCsUEhIFJ9cMrW9GC8goWA07a4+hCEVYT6EEmONO5JYETfXVTBDlqiz4RhJpwo87+K1iMvxJkGiATsK9babnNmQ/eWP78IC8L6Bf0t+HxA5sw0UDF6WMoH9mJSeuyqxZDRMSqkH+BHhkMjv+0ADIHDXa7hflEXu0Tu7fsWCNQ6PF0lN5ptiT57J2iNZ2jxKq9zj/Zz/+xmvhVHuVc4MFaC2n1PCOoHzC7/tCEA='
    password: '{cipher}AQBtvdEaXCf0crPI9dCP3fjsMIxqxrUwmYNmGID0v2RMLE/y3eRzQ+WRjf5GvnzKsJApLdtCOeLmvhH/dJD1UdM3AD0sR7NmTbByw8CcQ+rOfNKTcR3aTD28pQ/uoBLo6Y9skSyCQkZh+8Vfx7S3/4+3v2hoE0ZoUq5XGAK2WyS9d4kvODngGFagkfx34DbDFhx30wOra1raYCgQeFDxM96eOa2gnjt2TIF5u7YkSeazKhRr3wJ5MtM5qxAAWVL5wtr2HlDKBSUaBKnYs23rs4w7U5zmb7QMtiiyGQzmXQoHSanIqe+340vohAEDVKcjlzAHHQN31tX1oyDVz5oDjJObg7yM+xHUoJHyaiCqZ5VxnARCgkQZgsuBxUJ/eUQs0q0='
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
        
        # 配置初始化大小（默认0）、最小、最大（默认8） 
    initial-size: 1 
    min-idle: 1 
    max-active: 20 
        # 配置获取连接等待超时的时间 
    max-wait: 60000 
        # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大。 默认为false 
    pool-prepared-statements: true 
        # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。 
    max-open-prepared-statements: 20 
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
    time-between-eviction-runs-millis: 60000 
        # 配置一个连接在池中最小和最大生存的时间，单位是毫秒 
    min-evictable-idle-time-millis: 300000 
    max-evictable-idle-time-millis: 900000 
        # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。 
        # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。 
    validation-query: SELECT 1 
        # 申请连接时执行validationQuery检测连接是否有效 默认为true 
    test-on-borrow: true 
        # 归还连接时执行validationQuery检测连接是否有效 默认为false 
    test-on-return: false 
        # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-while-idle: true
        
## 该配置节点为独立的节点
mybatis:
   mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
   type-aliases-package: com.cht.spring.cloud.config.client.model  # 注意：对应实体类的路径
